apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: demo-cluster
  namespace: demo-cluster
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["10.244.0.0/16"]
    serviceDomain: "cluster.local"
    services:
      cidrBlocks: ["10.96.0.0/12"]
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: demo-cluster-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: LibvirtCluster
    name: demo-cluster-libvirt
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: LibvirtCluster
metadata:
  name: demo-cluster-libvirt
  namespace: demo-cluster
spec:
  #  TCP host
  uri: qemu+tcp:///system
  network: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: LibvirtMachineTemplate
metadata:
  name: demo-cp-template
  namespace: demo-cluster
spec:
  template:
    spec:
      image: /var/lib/libvirt/images/ubuntu-22.04-cloudimg.qcow2
      cpu: 2
      memoryMiB: 2048
      network: default
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: demo-cluster-control-plane
  namespace: demo-cluster
spec:
  replicas: 1
  version: v1.31.2
  machineTemplate:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: demo-cluster
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: LibvirtMachineTemplate
      name: demo-cp-template
      namespace: demo-cluster
    nodeDrainTimeout: 5m
  kubeadmConfigSpec:
    clusterConfiguration: {}
    initConfiguration: {}
    joinConfiguration: {}
# ---
# # Worker Node MachineTemplate
# apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
# kind: LibvirtMachineTemplate
# metadata:
#   name: demo-worker-template
#   namespace: demo-cluster
# spec:
#   template:
#     spec:
#       image: /var/lib/libvirt/images/ubuntu-22.04-cloudimg.qcow2
#       cpu: 2
#       memoryMiB: 2048
#       network: default
# ---
# # MachineDeployment
# apiVersion: cluster.x-k8s.io/v1beta1
# kind: MachineDeployment
# metadata:
#   name: demo-worker-deployment
#   namespace: demo-cluster
# spec:
#   clusterName: demo-cluster
#   replicas: 2
#   selector:
#     matchLabels:
#       nodepool: worker
#   template:
#     metadata:
#       labels:
#         cluster.x-k8s.io/cluster-name: demo-cluster
#         nodepool: worker
#     spec:
#       version: v1.31.0
#       clusterName: demo-cluster
#       bootstrap:
#         configRef:
#           apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
#           kind: KubeadmConfigTemplate
#           name: demo-worker-bootstrap
#       infrastructureRef:
#         apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
#         kind: LibvirtMachineTemplate
#         name: demo-worker-template
#         namespace: demo-cluster
# ---
# # Worker Bootstrap（KubeadmConfigTemplate）
# apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
# kind: KubeadmConfigTemplate
# metadata:
#   name: demo-worker-bootstrap
#   namespace: demo-cluster
# spec:
#   template:
#     spec:
#       joinConfiguration: {}
