apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: lv-demo
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: LibvirtMachineTemplate
    name: lv-demo-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: LibvirtCluster
    name: lv-demo
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: LibvirtCluster
metadata:
  name: lv-demo
  namespace: default
spec:
  network: default
  uri: qemu+tcp://192.168.122.1/system
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: LibvirtMachineTemplate
metadata:
  name: lv-demo-control-plane
  namespace: default
spec:
  template:
    spec:
      cpu: 2
      image: http://192.168.122.1/images/ubuntu-22.04.qcow2
      memoryMiB: 2048
      network: default
