# This rule is not used by the project cluster-api-provider-libvirt itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over infrastructure.libvirt.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-libvirt
    app.kubernetes.io/managed-by: kustomize
  name: libvirtcluster-admin-role
rules:
- apiGroups:
  - infrastructure.libvirt.io
  resources:
  - libvirtclusters
  verbs:
  - '*'
- apiGroups:
  - infrastructure.libvirt.io
  resources:
  - libvirtclusters/status
  verbs:
  - get
