apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: lv-demo
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    services:
      cidrBlocks: ["10.96.0.0/12"]
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: LibvirtMachineTemplate
    name: lv-demo-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: LibvirtCluster
    name: lv-demo
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: LibvirtCluster
metadata:
  name: lv-demo
spec:
  uri: qemu+tcp://192.168.122.1/system   # libvirt URI（改成你的）
  network: default                       # libvirt network 名稱
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: LibvirtMachineTemplate
metadata:
  name: lv-demo-control-plane
spec:
  template:
    spec:
      image: http://192.168.122.1/images/ubuntu-22.04.qcow2
      cpu: 2
      memoryMiB: 2048
      network: default
